defaults: &defaults
  application:
    name: "Fabuloso"
    version: "0.0.6"
    started_at: "12/07/2016"
    updated_at: "25/07/2016"
  default_style: "active"
  ldap:
    host: "127.0.0.1"
    port: 000
    domain: "your domain"
    default_pwd: "your password"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
